### ISSUE TITLE
The Gene Modifier, Mutations, Electric Fences, And Other Things

### ISSUE THREAD

**Issue by nunezjl** [FossilsArcheologyRevival/FossilArcheology1.6#340]
Hello I'm nunezjl, and I thought of some ideas I'd like to share with the fossils and archaeology community, this thread focuses on mutations and machines.

Anyways let's begin

1. The DNA Modifier

This block allows full customization on how your dinos look  when you click on the block a GUI will appear that has a slot of a egg once you place the egg in there it will show the dinosaur that is inside the egg you have a option to customize its appearance, there are 3 tabs on the top the first 2 allow you to pick a skin and the color of it the second allows you to color the stripes on the skin. The third tab allows you to choose what color you want the egg to be and once you click the check mark on each of the tabs, you can't go back, you can take the egg now and now you can't put it back. If the mob was a horse it will just give you 1 tab that allows you to choose which horse skin you get

2. Mutations

This feature allows your dinosaur to change its skin, it's form or the type.
For instance if you have a triceratops it has a 1/10 chance of changing the skin of the Dino, at random.
But there is a 2/20 chance it will be a failursaurus. But after that there is a 7/50 chance of getting a subspecies, for a triceratops, the only other Dino's it could mutate into are ceratopsians like protoceratops, styracosaurus, etc.

3. Better Analyzer And Cultivator Models

For the analyzer the block would turn into a block that is 2 long and has a hole in the middle at the top of the machine it would have the green button for when it's full it would go off.
For the cultivator maybe we can get a translucent with a DNA embryo in it and as the process goes on it changes slowly into a egg.

3. Electric Fences

This can be for aesthetics or protection from against dinosaurs and people but the would have to be power by red stone.

4. Dilo Anti Venom Tranq Darts And Tranq Dart Rifle

A gun to put all Dino's to sleep all expect Tyrannosaurus rex, obtained by dilolphosaurus spitting and missing and it landing on a block and right clicking on it with a sword

5. Tar Analyzable

Putting tar into a analyzer can give you mammal DNA, bio-fossils, and frozen meat

And that's it please leave feedback thank you bye!

**Comment by AlexModGuy** [comment]
1. No hybrids ever.
2. egh... Electric fences are sort of lame.
