### ISSUE TITLE
hadrosaur

### ISSUE THREAD

**Issue by mcblegal12345** [FossilsArcheologyRevival/FossilArcheology1.6#373]
for the next update put the hadrosaur with skin mod prehistoric

**Comment by dy126800** [comment]
Yeah we need more herbivorous dinosaurs.

**Comment by JTGhawk137** [comment]
I might put a hadrosaur in there, thanks for the idea :)

**Comment by AlexModGuy** [comment]
You can't tell me what to do! :P
